#include <iostream>
#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>
#include "calc.cpp"
#include "converter.c"
#include "random.c"
#include "Todo/todo.c"
#include "timer.cpp"
#include "secsmer.cpp"